### ISSUE TITLE
Integer values not valid as default parameter values

### ISSUE THREAD

**Issue by greg-wiltshire** [finos/tracdap#218]
### Steps to Reproduce:

Define a python model parameter as:

```
        return trac.define_parameters(
            trac.P("test_parameter", trac.FLOAT, label="Test parameter", default_value=100)
        )
```

### Expected Result:
When loading the model via the orch service this  model should load without error.

### Actual Result:

```
2022-12-08 00:21:22.459 INFO  [orch-svc-4-22   ] o.f.t.c.v.Validator - VALIDATION START: [ObjectDefinition STATIC]
2022-12-08 00:21:22.468 ERROR [orch-svc-4-22   ] o.f.t.c.v.Validator - model.parameters[test_parameter].defaultValue.type: Value does not match the expected type
2022-12-08 00:21:22.468 ERROR [orch-svc-4-22   ] o.f.t.c.v.Validator - model.parameters[test_parameter].defaultValue: Value does not match the expected type
2022-12-08 00:21:22.468 ERROR [orch-svc-4-22   ] o.f.t.c.v.Validator - VALIDATION FAILED: [ObjectDefinition STATIC]
2022-12-08 00:21:22.471 ERROR [orch-svc-4-22   ] o.f.t.s.o.s.JobManagementService - Job [JOB-be996614-27df-47db-a026-9a58b32724f6-v1] succeeded but the response could not be processed
org.finos.tracdap.common.exception.EInputValidation: There were multiple validation errors
model.parameters[test_parameter].defaultValue.type: Value does not match the expected type
model.parameters[test_parameter].defaultValue: Value does not match the expected type
	at org.finos.tracdap.common.validation.Validator.doValidation(Validator.java:78) ~[tracdap-lib-validation-0.5.0-rc.4.jar:?]
	at org.finos.tracdap.common.validation.Validator.validateFixedObject(Validator.java:50) ~[tracdap-lib-validation-0.5.0-rc.4.jar:?]
	at org.finos.tracdap.svc.orch.service.JobManagementService.recordJobResult(JobManagementService.java:222) ~[tracdap-svc-orch-0.5.0-rc.4.jar:0.5.0-rc.4]
	at org.finos.tracdap.svc.orch.service.JobManagementService.jobOperation(JobManagementService.java:283) ~[tracdap-svc-orch-0.5.0-rc.4.jar:0.5.0-rc.4]
	at org.finos.tracdap.svc.orch.service.JobManagementService.lambda$pollJobCache$2(JobManagementService.java:113) ~[tracdap-svc-orch-0.5.0-rc.4.jar:0.5.0-rc.4]
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98) ~[netty-common-4.1.80.Final.jar:4.1.80.Final]
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:153) ~[netty-common-4.1.80.Final.jar:4.1.80.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174) ~[netty-common-4.1.80.Final.jar:4.1.80.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167) ~[netty-common-4.1.80.Final.jar:4.1.80.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470) ~[netty-common-4.1.80.Final.jar:4.1.80.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569) ~[netty-transport-4.1.80.Final.jar:4.1.80.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[netty-common-4.1.80.Final.jar:4.1.80.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.80.Final.jar:4.1.80.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.80.Final.jar:4.1.80.Final]
	at java.lang.Thread.run(Thread.java:831) ~[?:?]
```

### Environment:
tracdap-runtime==0.5.0
@finos/tracdap-web-api": "^0.5.0
tracdap-sandbox-0.5.0-rc.4

### Additional Context:

Making the default value to 100.0 fixes this issue but I think that 100 should be a valid float default value.

**Comment by mslapek** [comment]
@martin-traverse  Where should be the casting from `Int` to `Float`?

In Java backend or Python codebase?
